#!/usr/bin/env perl

use lib qw(./lib /home/fatty/workspace/TestApp/lib);
use FCJ;
use FCJ::Info;
use DBI;
use Ext::Schema;
use feature qw(say);

my $fcj = FCJ->new(ttf=>"freesansbold.ttf");

my $db = Ext::Schema->connect( {
    dsn => 'dbi:mysql:database=control_center',
    user => 'ccuser',
    password => 'borgles',
});

my $offset = 275;

my $cou = $db->resultset("PornhubComment")->count();
my $s = 1;
while ($s<1000) {
	my $txt = $db->resultset("PornhubComment")->search({},{rows=>1,page=>int(rand($cou))})->first->commment;

	my $img = $fcj->render(text=>$txt);
	if ($img) {
		$s++;
		say "Writing image ".($s+$offset);
		$img->Write("out/".($s+$offset).".jpg");
	}
}


